[versions]
managed-mqttv3 = "1.2.5"
managed-mqttv5 = "1.2.5"

awaitility = "4.2.0"
bcpkix-jdk15on = "1.70"
kotlin = "1.6.21"
testcontainers = "1.17.1"
spock = "2.0-groovy-3.0"

[libraries]
managed-paho-mqttv3-client = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "managed-mqttv3" }
managed-paho-mqttv5-client = { module = "org.eclipse.paho:org.eclipse.paho.mqttv5.client", version.ref = "managed-mqttv5" }

awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
bcpkix-jdk15on = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bcpkix-jdk15on" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
reactor-core = { module = "io.projectreactor:reactor-core" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
testcontainers-spock = { module = "org.testcontainers:spock", version.ref = "testcontainers" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
